/**
 * Shared timeout constants for generation reference-image preparation stages.
 */
export const FETCH_LOCAL_IMAGE_TIMEOUT_MS = 12_000;
export const PREPARE_REFERENCE_IMAGE_UPLOAD_TIMEOUT_MS = 20_000;
export const UPLOAD_REFERENCE_IMAGE_STORAGE_TIMEOUT_MS = 90_000;
export const STAGE_REFERENCE_IMAGE_UPLOAD_TIMEOUT_MS = 60_000;
export const REFERENCE_IMAGE_UPLOAD_PIPELINE_TIMEOUT_MS =
  PREPARE_REFERENCE_IMAGE_UPLOAD_TIMEOUT_MS +
  UPLOAD_REFERENCE_IMAGE_STORAGE_TIMEOUT_MS +
  STAGE_REFERENCE_IMAGE_UPLOAD_TIMEOUT_MS;
export const SIGNED_URL_REFRESH_TIMEOUT_MS = 10_000;
