import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type Dispatch,
  type SetStateAction,
} from "react";
import type { InternalMediaRef } from "../../../lib/media/internalMediaRefs";
import { StudioOutput, type ToolId } from "../types";
import { resolvePreviewUrlById } from "../logic/stateParsers";
import { useAiStudioCreationState } from "./useAiStudioCreationState";
import { useAiStudioClearGenerationOutput } from "./useAiStudioClearGenerationOutput";
import { useAiStudioOutputDerivations } from "./useAiStudioOutputDerivations";
import { useAiStudioReferenceGridStateActions } from "./useAiStudioReferenceGridStateActions";
import { useAiStudioReferenceSelectionState } from "./useAiStudioReferenceSelectionState";
import { useAiStudioWorkflowSettings } from "./useAiStudioWorkflowSettings";
import { useAiStudioStateEffects } from "./useAiStudioStateEffects";
import { useAiStudioOutputCollectionState } from "./useAiStudioOutputCollectionState";
import { useAiStudioOutputPersistenceEffects } from "./useAiStudioOutputPersistenceEffects";
import { useAiStudioReferenceGridPreviewState } from "./useAiStudioReferenceGridPreviewState";
import {
  getDefaultDurationSecondsForModel,
  IMAGE_RESOLUTION_STORAGE_KEY,
  VIDEO_DURATION_STORAGE_KEY,
  VIDEO_RESOLUTION_STORAGE_KEY,
} from "./aiStudioStateConfig";
import { useAiStudioCreateRuntimePromptState } from "./useAiStudioCreateRuntimePromptState";
import { useAiStudioStateOutputControllers } from "./useAiStudioStateOutputControllers";
import { useAiStudioGeneratedOutputMaintenance } from "./useAiStudioGeneratedOutputMaintenance";
import { useAiStudioRuntimeAuthorityUiState } from "./useAiStudioRuntimeAuthorityUiState";
import { useAiStudioStateRuntimeControllers } from "./useAiStudioStateRuntimeControllers";
import { useAiStudioStateSupportControllers } from "./useAiStudioStateSupportControllers";
import {
  createEmptyReferenceProjectionState,
  type ReferenceProjectionState,
} from "../reference-projections";

export const useAiStudioState = ({
  projectId = null,
  projectRouteRequested = false,
  sessionId = null,
  isCharacterModeEnabled = false,
  selectedStylePrompt = null,
  selectedStyleContext = null,
  expertCreateMode = "standard",
  activePulsePresetId = null,
  pulseSessionInstanceId = null,
  setExpertCreateMode,
  setActivePulsePresetId,
  setPulseSessionInstanceId,
}: {
  projectId?: string | null;
  projectRouteRequested?: boolean;
  sessionId?: string | null;
  isCharacterModeEnabled?: boolean;
  selectedStylePrompt?: string | null;
  selectedStyleContext?: StudioOutput["styleContext"] | null;
  expertCreateMode?: "standard" | "pulse";
  activePulsePresetId?: string | null;
  pulseSessionInstanceId?: string | null;
  setExpertCreateMode?: Dispatch<SetStateAction<"standard" | "pulse">>;
  setActivePulsePresetId?: Dispatch<SetStateAction<string | null>>;
  setPulseSessionInstanceId?: Dispatch<SetStateAction<string | null>>;
} = {}) => {
  const {
    promptRef,
    mode,
    setMode,
    aspect,
    setAspect,
    model,
    setModelState,
    standardPrompt,
    setStandardPrompt,
    pulsePrompt,
    setPulsePrompt,
    editReferenceText,
    setEditReferenceTextState,
    videoReferenceText,
    setVideoReferenceTextState,
    musicPromptDraft,
    setMusicPromptDraftState,
    musicLyricsDraft,
    setMusicLyricsDraftState,
    musicDurationSeconds,
    setMusicDurationSecondsState,
    soundEffectsPromptDraft,
    setSoundEffectsPromptDraftState,
    soundEffectsDurationSeconds,
    setSoundEffectsDurationSecondsState,
    voiceDesignPromptDraft,
    setVoiceDesignPromptDraftState,
    voiceScriptDraft,
    setVoiceScriptDraftState,
    expertEditSessionState,
    setExpertEditSessionState,
    publishExpertEditSessionState,
    getExpertEditSessionState,
    expertEditSessionRevision,
    videoReferenceMode,
    setVideoReferenceMode,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    hasUserVideoPrefs,
    setHasUserVideoPrefs,
    videoGenerateAudio,
    setVideoGenerateAudio,
    videoCameraFixed,
    setVideoCameraFixed,
    videoAutoFix,
    setVideoAutoFix,
    klingNegativePrompt,
    setKlingNegativePrompt,
    klingCfgScale,
    setKlingCfgScale,
    klingWorkflowMode,
    setKlingWorkflowMode,
    seedance2InputMode,
    setSeedance2InputMode,
    seedance2ReferenceImageUrls,
    setSeedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    setSeedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    setSeedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    setSeedance2ReturnLastFrame,
    seedance2WebSearch,
    setSeedance2WebSearch,
    klingShotType,
    setKlingShotType,
    klingVoiceIds,
    setKlingVoiceIds,
    klingMultiPrompts,
    setKlingMultiPrompts,
    klingElements,
    setKlingElements,
    createIsGenerating,
    editIsGenerating,
    videoIsGenerating,
    beginPanelGeneration,
    endPanelGeneration,
    uiError,
    setUiError,
    uiNotice,
    setUiNotice,
    lastVideoReferenceModeRef,
    lastNonKling3VideoModelRef,
    lastNonKeyframesVideoModelRef,
    lastNonMotionVideoModelRef,
  } = useAiStudioCreationState({
    projectRouteRequested,
  });

  const baseRuntimeAuthorityKey =
    projectRouteRequested && !projectId
      ? "project:pending"
      : projectId
        ? `project:${projectId}`
        : sessionId
          ? `session:${sessionId}`
          : "session:pending";
  const runtimeAuthorityKey = baseRuntimeAuthorityKey;
  const createModeRuntimeAuthorityKey = `${baseRuntimeAuthorityKey}:create:${expertCreateMode}`;

  const {
    activeOutputState,
    setActiveOutputState,
    archivedOutputState,
    setArchivedOutputState,
    activeOutputByIdRef,
    outputs,
    archivedOutputs,
    activeOutputById,
    setOutputsState,
    setArchivedOutputs,
    setOutputCollectionsForAuthority,
  } = useAiStudioOutputCollectionState({
    authorityKey: runtimeAuthorityKey,
  });
  const [activeOutputId, setActiveOutputId] = useState<string | null>(null);
  const [referenceProjectionState, setReferenceProjectionState] =
    useState<ReferenceProjectionState>(createEmptyReferenceProjectionState);
  const referenceProjectionStateRef = useRef<ReferenceProjectionState>(referenceProjectionState);
  const curatedReferenceIds = referenceProjectionState.quickSlotIds;
  const removedFromAllRefsIds = referenceProjectionState.removedFromAllRefsIds;
  const [saved, setSaved] = useState(false);
  const pendingAutoSavesRef = useRef<Record<string, unknown>>({});
  const pendingFinalizeRemovalIdsRef = useRef<Set<string>>(new Set());
  const sessionHydrationSigningRevisionRef = useRef(0);
  const { setOutputCollectionsForCreateMode, setRuntimeUiStateForCreateMode } =
    useAiStudioRuntimeAuthorityUiState({
      activeOutputId,
      baseRuntimeAuthorityKey,
      referenceProjectionState,
      runtimeAuthorityKey,
      saved,
      sessionHydrationSigningRevisionRef,
      setActiveOutputId,
      setOutputCollectionsForAuthority,
      setReferenceProjectionState,
      setSaved,
    });

  useEffect(() => {
    pendingAutoSavesRef.current = {};
    pendingFinalizeRemovalIdsRef.current = new Set();
  }, [runtimeAuthorityKey]);

  const {
    activeOutput,
    activeOutputPreviewUrl,
    markReferenceGridReady,
    referenceGridReadyOutputIds: visibleReferenceGridReadyOutputIds,
  } = useAiStudioReferenceGridPreviewState({
    activeOutputById,
    activeOutputId,
    outputs,
    archivedOutputs,
  });
  const singleImageContextOutput = (() => {
    if (activeOutput) return activeOutput;
    const imageOutputs = outputs.filter((output) => output.mode === "image" && output.previewUrl);
    return imageOutputs.length === 1 ? (imageOutputs[0] ?? null) : null;
  })();
  const {
    selectedTool,
    setSelectedTool,
    showCreateTools,
    setShowCreateTools,
    imageReferenceImageUrl,
    imageExtraImageUrls,
    videoReferenceImageUrl,
    videoExtraImageUrls,
    motionReferenceVideoUrl,
    setMotionReferenceVideoUrl,
    useReferenceImageIndicator,
    setUseReferenceImageIndicator,
    detailOutputId,
    setDetailOutputId,
    referenceImageUrl,
    setReferenceImageUrl,
    setImageReferenceImageUrl,
    setVideoReferenceImageUrl,
    extraImageUrls,
    setExtraImageUrl,
    setImageExtraImageUrl,
    setVideoExtraImageUrl,
    clearReferenceImages,
    toggleReferenceIndicator,
    resolveReferenceInputsForTool,
    isModelModalOpen,
    modelModalAnchor,
    modelModalContext,
    setIsModelModalOpen,
    setModelModalAnchor,
    openModelModal,
    closeModelModal,
    setAuthorityState: setReferenceSelectionAuthorityState,
    getAuthorityState: getReferenceSelectionAuthorityState,
  } = useAiStudioReferenceSelectionState({
    activeOutputPreviewUrl,
    authorityKey: createModeRuntimeAuthorityKey,
  });

  const setReferenceSelectionStateForCreateMode = useCallback(
    (
      createMode: "standard" | "pulse",
      nextState: {
        selectedTool: ToolId | null;
        showCreateTools?: boolean;
        referenceImageUrl: string | null;
        extraImageUrls: [string | null, string | null, string | null];
        referenceImageInternalMediaRefs?: Array<InternalMediaRef | null>;
        motionReferenceVideoUrl: string | null;
        useReferenceImageIndicator?: boolean;
        detailOutputId?: string | null;
      }
    ) => {
      setReferenceSelectionAuthorityState(
        `${baseRuntimeAuthorityKey}:create:${createMode}`,
        nextState
      );
    },
    [baseRuntimeAuthorityKey, setReferenceSelectionAuthorityState]
  );

  const getReferenceSelectionStateForCreateMode = useCallback(
    (createMode: "standard" | "pulse") =>
      getReferenceSelectionAuthorityState(`${baseRuntimeAuthorityKey}:create:${createMode}`),
    [baseRuntimeAuthorityKey, getReferenceSelectionAuthorityState]
  );

  const { detailOutput, currentModelLabel, isPrimaryEditStageGenerating } =
    useAiStudioOutputDerivations({ outputs, activeOutputById, detailOutputId, model });
  const { hasPendingWorkflowRestore } = useAiStudioWorkflowSettings({
    projectId,
    projectRouteRequested,
    sessionId,
    isCharacterModeEnabled,
    selectedTool,
    mode,
    model,
    aspect,
    imageResolution,
    videoReferenceMode,
    videoDurationSeconds,
    videoResolution,
    videoGenerateAudio,
    videoCameraFixed,
    videoAutoFix,
    klingNegativePrompt,
    klingCfgScale,
    klingWorkflowMode,
    seedance2InputMode,
    seedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    seedance2WebSearch,
    klingShotType,
    klingVoiceIds,
    klingMultiPrompts,
    klingElements,
    setMode,
    setModelState,
    setAspect,
    setImageResolution,
    setVideoReferenceMode,
    setVideoDurationSeconds,
    setVideoResolution,
    setVideoGenerateAudio,
    setVideoCameraFixed,
    setVideoAutoFix,
    setKlingNegativePrompt,
    setKlingCfgScale,
    setKlingWorkflowMode,
    setSeedance2InputMode,
    setSeedance2ReferenceImageUrls,
    setSeedance2ReferenceVideoUrls,
    setSeedance2ReferenceAudioUrls,
    setSeedance2ReturnLastFrame,
    setSeedance2WebSearch,
    setKlingShotType,
    setKlingVoiceIds,
    setKlingMultiPrompts,
    setKlingElements,
  });
  const {
    activeCreatePrompt,
    createStatePrompts,
    createStateRuntime,
    setSharedPrompt,
    setStandardCreatePrompt,
    setPulseCreatePrompt,
    setEditReferenceText,
    setMusicLyricsDraft,
    setMusicPromptDraft,
    setSoundEffectsPromptDraft,
    setVideoReferenceText,
    setVoiceDesignPromptDraft,
    setVoiceScriptDraft,
  } = useAiStudioCreateRuntimePromptState({
    activePulsePresetId,
    expertCreateMode,
    setMusicPromptDraftState,
    setMusicLyricsDraftState,
    setSoundEffectsPromptDraftState,
    setVoiceDesignPromptDraftState,
    setVoiceScriptDraftState,
    pulsePrompt,
    pulseSessionInstanceId,
    setEditReferenceTextState,
    setPulsePromptState: setPulsePrompt,
    setStandardPromptState: setStandardPrompt,
    setVideoReferenceTextState,
    standardPrompt,
  });
  const {
    restoreArchivedOutput,
    restoreAllArchivedOutputs,
    setOutputs,
    addCuratedReference,
    removeCuratedReference,
    reorderCuratedReference,
    removeReferencesForDeletedMedia,
    clearCuratedReferences,
    resetReferenceGridState,
  } = useAiStudioReferenceGridStateActions({
    outputs,
    archivedOutputs,
    outputsLength: outputs.length,
    setActiveOutputId,
    setOutputsState,
    setArchivedOutputs,
    setReferenceProjectionState,
    pendingFinalizeRemovalIdsRef,
  });
  useAiStudioStateEffects({
    promptRef,
    aspect,
    setAspect,
    activeOutputPreviewUrl,
    setUseReferenceImageIndicator,
    model,
    referenceImageUrl,
    extraImageUrls,
    selectedTool,
    videoReferenceMode,
    setVideoReferenceMode,
    setModel: setModelState,
    lastVideoReferenceModeRef,
    lastNonKling3VideoModelRef,
    lastNonKeyframesVideoModelRef,
    lastNonMotionVideoModelRef,
    showCreateTools,
    setShowCreateTools,
    videoDurationStorageKey: VIDEO_DURATION_STORAGE_KEY,
    videoResolutionStorageKey: VIDEO_RESOLUTION_STORAGE_KEY,
    imageResolutionStorageKey: IMAGE_RESOLUTION_STORAGE_KEY,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    hasUserVideoPrefs,
    setHasUserVideoPrefs,
    setVideoGenerateAudio,
    isCharacterModeEnabled,
    mode,
    setDetailOutputId,
    setIsModelModalOpen,
    setModelModalAnchor,
    hasPendingWorkflowRestore,
  });

  useAiStudioOutputPersistenceEffects({
    outputs,
    archivedOutputs,
    setOutputsState,
    setArchivedOutputs,
    referenceProjectionState,
    setReferenceProjectionState,
    referenceProjectionStateRef,
    activeOutputOrder: activeOutputState.order,
    archivedOutputOrder: archivedOutputState.order,
    curatedReferenceIds,
    setActiveOutputState,
    setArchivedOutputState,
  });
  useAiStudioGeneratedOutputMaintenance({
    baseRuntimeAuthorityKey,
    hasPendingWorkflowRestore,
    outputs,
    projectId,
    projectRouteRequested,
    setOutputsState,
  });

  const {
    deleteOutput,
    ensureGenerationRecord,
    ensureOutputPersisted,
    findOutputById,
    forceDeleteOutput,
    notifyGenerationFailure,
    saveActiveOutput,
    savePromptToLibrary,
    saveReferenceToLibrary,
    updateOutputById,
    updateOutputPrompt,
  } = useAiStudioStateOutputControllers({
    activeOutputByIdRef,
    activeOutputId,
    aspect,
    model,
    pendingAutoSavesRef,
    pendingFinalizeRemovalIdsRef,
    projectId,
    createPrompt: activeCreatePrompt,
    quickSlotIds: referenceProjectionState.quickSlotIds,
    setActiveOutputId,
    setActiveOutputState,
    setOutputs,
    setReferenceProjectionState,
    setSaved,
    setUiError,
    outputs,
  });

  const {
    buildSessionSnapshot,
    generateOutput,
    handleReferenceOutputMediaLoaded,
    hydrateFromSessionSnapshot,
    insertOptimisticGenerationPlaceholder,
    regenerateOutput,
    removeOptimisticGenerationPlaceholder,
    rerollOutputFromReplay,
    retryOutputStatus,
    abandonTaskOutput,
  } = useAiStudioStateRuntimeControllers({
    activeOutputId,
    activeOutputPreviewUrl,
    archivedOutputs,
    aspect,
    createPrompts: createStatePrompts,
    createRuntime: createStateRuntime,
    curatedReferenceIds,
    editReferenceText,
    extraImageUrls,
    findOutputById,
    imageResolution,
    klingCfgScale,
    klingElements,
    klingMultiPrompts,
    klingNegativePrompt,
    klingShotType,
    klingVoiceIds,
    klingWorkflowMode,
    markReferenceGridReady,
    mode,
    model,
    motionReferenceVideoUrl,
    notifyGenerationFailure,
    outputs,
    projectId,
    referenceImageUrl,
    removedFromAllRefsIds,
    resolveReferenceInputsForTool,
    seedance2InputMode,
    seedance2ReferenceAudioUrls,
    seedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    seedance2ReturnLastFrame,
    seedance2WebSearch,
    selectedStyleContext,
    selectedStylePrompt,
    selectedTool,
    sessionHydrationSigningRevisionRef,
    setActivePulsePresetId: setActivePulsePresetId ?? (() => undefined),
    setArchivedOutputs,
    setAspect,
    setEditReferenceText,
    setExpertCreateMode: setExpertCreateMode ?? (() => undefined),
    setExtraImageUrl,
    setImageReferenceImageUrl,
    setImageResolution,
    setKlingCfgScale,
    setKlingElements,
    setKlingMultiPrompts,
    setKlingNegativePrompt,
    setKlingShotType,
    setKlingVoiceIds,
    setKlingWorkflowMode,
    setMode,
    setModel: setModelState,
    setMotionReferenceVideoUrl,
    setOutputCollectionsForCreateMode,
    setOutputs,
    setOutputsState,
    beginPanelGeneration,
    endPanelGeneration,
    setPulseCreatePrompt,
    setPulseSessionInstanceId: setPulseSessionInstanceId ?? (() => undefined),
    setReferenceImageUrl,
    setReferenceSelectionStateForCreateMode,
    getReferenceSelectionStateForCreateMode,
    setRuntimeUiStateForCreateMode,
    setSaved,
    setSeedance2InputMode,
    setSeedance2ReferenceAudioUrls,
    setSeedance2ReferenceImageUrls,
    setSeedance2ReferenceVideoUrls,
    setSeedance2ReturnLastFrame,
    setSeedance2WebSearch,
    setSelectedTool,
    setStandardCreatePrompt,
    setUiError,
    setUiNotice,
    setVideoAutoFix,
    setVideoCameraFixed,
    setVideoDurationSeconds,
    setVideoGenerateAudio,
    setVideoReferenceMode,
    setVideoReferenceText,
    setVideoResolution,
    updateOutputById,
    useReferenceImageIndicator,
    videoAutoFix,
    videoCameraFixed,
    videoDurationSeconds,
    videoGenerateAudio,
    videoReferenceImageUrl,
    videoReferenceMode,
    videoReferenceText,
    videoResolution,
    ensureGenerationRecord,
  });

  const clearGenerationOutput = useAiStudioClearGenerationOutput({
    abandonTaskOutput,
    findOutputById,
    forceDeleteOutput,
    setActiveOutputId,
    updateOutputById,
  });

  const {
    addAgentPromptReference,
    addPastedPromptReference,
    addPastedMediaReference,
    insertPastedMediaReference,
    addLibraryMediaReference,
    addLibraryMediaReferenceToQuickSlot,
    addLibraryPromptReference,
    addLibraryPromptReferenceToQuickSlot,
    ingestReferenceFiles,
    addOutputsFromFiles,
    getAgentContext,
    getOutputById,
    getOutputSnapshot,
    selectActiveOutputs,
    selectArchivedOutputs,
    selectOutputById,
    subscribeOutputs,
  } = useAiStudioStateSupportControllers({
    activeOutput: singleImageContextOutput,
    archivedOutputs,
    aspect,
    mode,
    model,
    outputs,
    projectId,
    setOutputs,
    setUiError,
    updateOutputById,
  });

  return {
    isPrimaryEditStageGenerating,
    promptRef,
    mode,
    setMode: setMode,
    aspect,
    setAspect,
    model,
    setModel: setModelState,
    currentModelLabel,
    activeCreatePrompt,
    setPrompt: setSharedPrompt,
    standardPrompt,
    pulsePrompt,
    setStandardCreatePrompt,
    setPulseCreatePrompt,
    outputs,
    outputOrder: activeOutputState.order,
    outputById: activeOutputState.byId,
    setOutputs,
    resetReferenceGridState,
    curatedReferenceIds,
    removedFromAllRefsIds,
    addCuratedReference,
    removeCuratedReference,
    reorderCuratedReference,
    removeReferencesForDeletedMedia,
    clearCuratedReferences,
    archivedOutputs,
    archivedOutputOrder: archivedOutputState.order,
    archivedOutputById: archivedOutputState.byId,
    selectActiveOutputs,
    selectArchivedOutputs,
    selectOutputById,
    getOutputById,
    subscribeOutputs,
    getOutputSnapshot,
    activeOutput,
    activeOutputId,
    setActiveOutputId,
    saved,
    setSaved,
    selectedTool,
    setSelectedTool,
    showCreateTools,
    setShowCreateTools,
    imageReferenceImageUrl,
    imageExtraImageUrls,
    videoReferenceImageUrl,
    videoExtraImageUrls,
    referenceImageUrl,
    setReferenceImageUrl,
    setImageReferenceImageUrl,
    setVideoReferenceImageUrl,
    extraImageUrls,
    setExtraImageUrl,
    setImageExtraImageUrl,
    setVideoExtraImageUrl,
    videoReferenceMode,
    setVideoReferenceMode,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    videoGenerateAudio,
    setVideoGenerateAudio,
    videoCameraFixed,
    setVideoCameraFixed,
    videoAutoFix,
    setVideoAutoFix,
    klingNegativePrompt,
    setKlingNegativePrompt,
    klingCfgScale,
    setKlingCfgScale,
    klingWorkflowMode,
    setKlingWorkflowMode,
    seedance2InputMode,
    setSeedance2InputMode,
    seedance2ReferenceImageUrls,
    setSeedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    setSeedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    setSeedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    setSeedance2ReturnLastFrame,
    seedance2WebSearch,
    setSeedance2WebSearch,
    klingShotType,
    setKlingShotType,
    klingVoiceIds,
    setKlingVoiceIds,
    klingMultiPrompts,
    setKlingMultiPrompts,
    klingElements,
    setKlingElements,
    createIsGenerating,
    editIsGenerating,
    videoIsGenerating,
    motionReferenceVideoUrl,
    setMotionReferenceVideoUrl,
    editReferenceText,
    setEditReferenceText,
    videoReferenceText,
    setVideoReferenceText,
    musicPromptDraft,
    setMusicPromptDraft,
    musicLyricsDraft,
    setMusicLyricsDraft,
    musicDurationSeconds,
    setMusicDurationSeconds: setMusicDurationSecondsState,
    soundEffectsPromptDraft,
    setSoundEffectsPromptDraft,
    soundEffectsDurationSeconds,
    setSoundEffectsDurationSeconds: setSoundEffectsDurationSecondsState,
    voiceDesignPromptDraft,
    setVoiceDesignPromptDraft,
    voiceScriptDraft,
    setVoiceScriptDraft,
    expertEditSessionState,
    setExpertEditSessionState,
    publishExpertEditSessionState,
    getExpertEditSessionState,
    expertEditSessionRevision,
    setSharedPrompt,
    resolvePreviewUrlById,
    useReferenceImageIndicator,
    detailOutput,
    detailOutputId,
    setDetailOutputId,
    isModelModalOpen,
    modelModalAnchor,
    modelModalContext,
    generateOutput,
    regenerateOutput,
    rerollOutputFromReplay,
    insertOptimisticGenerationPlaceholder,
    removeOptimisticGenerationPlaceholder,
    updateOutputById,
    notifyGenerationFailure,
    saveActiveOutput,
    ensureOutputPersisted,
    saveReferenceToLibrary,
    savePromptToLibrary,
    addAgentPromptReference,
    addPastedPromptReference,
    addPastedMediaReference,
    insertPastedMediaReference,
    addLibraryMediaReference,
    addLibraryMediaReferenceToQuickSlot,
    addLibraryPromptReference,
    addLibraryPromptReferenceToQuickSlot,
    ingestReferenceFiles,
    addOutputsFromFiles,
    buildSessionSnapshot,
    hydrateFromSessionSnapshot,
    toggleReferenceIndicator,
    clearReferenceImages,
    openModelModal,
    closeModelModal,
    updateOutputPrompt,
    deleteOutput,
    clearGenerationOutput,
    restoreArchivedOutput,
    restoreAllArchivedOutputs,
    uiError,
    setUiError,
    uiNotice,
    setUiNotice,
    getDefaultDurationSeconds: getDefaultDurationSecondsForModel,
    getAgentContext,
    onReferenceOutputMediaLoaded: handleReferenceOutputMediaLoaded,
    referenceGridReadyOutputIds: visibleReferenceGridReadyOutputIds,
    retryOutputStatus,
  };
};
