import { useCallback, type Dispatch, type SetStateAction } from "react";
import type { InternalMediaRef } from "../../../lib/media/internalMediaRefs";
import { StudioOutput, type ToolId } from "../types";
import { resolvePreviewUrlById } from "../logic/stateParsers";
import { useAiStudioCreationState } from "./useAiStudioCreationState";
import { useAiStudioClearGenerationOutput } from "./useAiStudioClearGenerationOutput";
import { useAiStudioOutputDerivations } from "./useAiStudioOutputDerivations";
import { useAiStudioReferenceGridStateActions } from "./useAiStudioReferenceGridStateActions";
import {
  useAiStudioReferenceSelectionState,
  type ReferenceSelectionAuthorityStateSeed,
} from "./useAiStudioReferenceSelectionState";
import { useAiStudioWorkflowSettings } from "./useAiStudioWorkflowSettings";
import { useAiStudioStateEffects } from "./useAiStudioStateEffects";
import { useAiStudioOutputPersistenceEffects } from "./useAiStudioOutputPersistenceEffects";
import { useAiStudioReferenceGridPreviewState } from "./useAiStudioReferenceGridPreviewState";
import {
  getDefaultDurationSecondsForModel,
  IMAGE_RESOLUTION_STORAGE_KEY,
  VIDEO_DURATION_STORAGE_KEY,
  VIDEO_RESOLUTION_STORAGE_KEY,
} from "./aiStudioStateConfig";
import { useAiStudioCreateRuntimePromptState } from "./useAiStudioCreateRuntimePromptState";
import { useAiStudioStateOutputControllers } from "./useAiStudioStateOutputControllers";
import { useAiStudioGeneratedOutputMaintenance } from "./useAiStudioGeneratedOutputMaintenance";
import { useAiStudioRuntimeAuthorityState } from "./useAiStudioRuntimeAuthorityState";
import { useAiStudioStateRuntimeControllers } from "./useAiStudioStateRuntimeControllers";
import { useAiStudioStateSupportControllers } from "./useAiStudioStateSupportControllers";
import { useAiStudioWorkflowReloadController } from "./useAiStudioWorkflowReloadController";
import { useAiStudioProjectWorkspaceCriticalSaveSignal } from "./useAiStudioProjectWorkspaceCriticalSaveSignal";
import type { VoiceChangerSource } from "../components/VoiceChangerSourceDropzone";

export const useAiStudioState = ({
  projectId = null,
  projectRouteRequested = false,
  sessionId = null,
  isCharacterModeEnabled = false,
  selectedStylePrompt = null,
  selectedStyleContext = null,
  expertCreateMode = "standard",
  activePulsePresetId = null,
  pulseSessionInstanceId = null,
  setExpertCreateMode,
  setActivePulsePresetId,
  setPulseSessionInstanceId,
  setVoiceChangerSource,
  prepareCreateCharacterWorkflowReload,
  prepareImageStyleWorkflowReload,
  prepareStandardCreateWorkflowReload,
}: {
  projectId?: string | null;
  projectRouteRequested?: boolean;
  sessionId?: string | null;
  isCharacterModeEnabled?: boolean;
  selectedStylePrompt?: string | null;
  selectedStyleContext?: StudioOutput["styleContext"] | null;
  expertCreateMode?: "standard" | "pulse";
  activePulsePresetId?: string | null;
  pulseSessionInstanceId?: string | null;
  setExpertCreateMode?: Dispatch<SetStateAction<"standard" | "pulse">>;
  setActivePulsePresetId?: Dispatch<SetStateAction<string | null>>;
  setPulseSessionInstanceId?: Dispatch<SetStateAction<string | null>>;
  setVoiceChangerSource?: (source: VoiceChangerSource | null) => void;
  prepareCreateCharacterWorkflowReload?: (
    characterContext: StudioOutput["characterContext"] | null
  ) => void;
  prepareImageStyleWorkflowReload?: (styleContext: StudioOutput["styleContext"] | null) => void;
  prepareStandardCreateWorkflowReload?: (prompt: string) => void;
} = {}) => {
  const {
    promptRef,
    mode,
    setMode,
    aspect,
    setAspect,
    model,
    setModelState,
    standardPrompt,
    setStandardPrompt,
    pulsePrompt,
    setPulsePrompt,
    editReferenceText,
    setEditReferenceTextState,
    videoReferenceText,
    setVideoReferenceTextState,
    musicPromptDraft,
    setMusicPromptDraftState,
    musicLyricsDraft,
    setMusicLyricsDraftState,
    musicDurationSeconds,
    setMusicDurationSecondsState,
    musicComposerMode,
    setMusicComposerModeState,
    musicInstrumentalEnabled,
    setMusicInstrumentalEnabledState,
    musicSingerEnabled,
    setMusicSingerEnabledState,
    musicSongBatchCount,
    setMusicSongBatchCountState,
    soundEffectsPromptDraft,
    setSoundEffectsPromptDraftState,
    soundEffectsDurationSeconds,
    setSoundEffectsDurationSecondsState,
    soundEffectsLoopEnabled,
    setSoundEffectsLoopEnabledState,
    voiceDesignPromptDraft,
    setVoiceDesignPromptDraftState,
    voiceScriptDraft,
    setVoiceScriptDraftState,
    voiceSelectedVoiceId,
    setVoiceSelectedVoiceIdState,
    expertEditSessionState,
    setExpertEditSessionState,
    publishExpertEditSessionState,
    getExpertEditSessionState,
    expertEditSessionRevision,
    videoReferenceMode,
    setVideoReferenceMode,
    lipSyncAudio,
    setLipSyncAudio,
    lipSyncTurboMode,
    setLipSyncTurboMode,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    hasUserVideoPrefs,
    setHasUserVideoPrefs,
    videoGenerateAudio,
    setVideoGenerateAudio,
    videoCameraFixed,
    setVideoCameraFixed,
    videoAutoFix,
    setVideoAutoFix,
    klingNegativePrompt,
    setKlingNegativePrompt,
    klingCfgScale,
    setKlingCfgScale,
    klingWorkflowMode,
    setKlingWorkflowMode,
    seedance2InputMode,
    setSeedance2InputMode,
    seedance2ReferenceImageUrls,
    setSeedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    setSeedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    setSeedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    setSeedance2ReturnLastFrame,
    seedance2WebSearch,
    setSeedance2WebSearch,
    klingShotType,
    setKlingShotType,
    klingVoiceIds,
    setKlingVoiceIds,
    klingMultiPrompts,
    setKlingMultiPrompts,
    klingElements,
    setKlingElements,
    createIsGenerating,
    editIsGenerating,
    videoIsGenerating,
    beginPanelGeneration,
    endPanelGeneration,
    uiError,
    setUiError,
    uiNotice,
    setUiNotice,
    lastVideoReferenceModeRef,
    lastNonKling3VideoModelRef,
    lastNonKeyframesVideoModelRef,
    lastNonMotionVideoModelRef,
    lastNonLipSyncVideoModelRef,
  } = useAiStudioCreationState({
    projectRouteRequested,
  });

  const {
    activeOutputById,
    activeOutputByIdRef,
    activeOutputId,
    activeOutputState,
    setActiveOutputState,
    archivedOutputState,
    setArchivedOutputState,
    outputs,
    archivedOutputs,
    setOutputsState,
    setArchivedOutputs,
    baseRuntimeAuthorityKey,
    beginManualWorkflowReload,
    createModeRuntimeAuthorityKey,
    curatedReferenceIds,
    manualWorkflowReloadRevision,
    pendingAutoSavesRef,
    pendingFinalizeRemovalIdsRef,
    referenceProjectionState,
    referenceProjectionStateRef,
    removedFromAllRefsIds,
    saved,
    sessionHydrationSigningRevisionRef,
    setActiveOutputId,
    setOutputCollectionsForCreateMode,
    setReferenceProjectionState,
    setRuntimeUiStateForCreateMode,
    setSaved,
    workspaceRuntimeKey,
  } = useAiStudioRuntimeAuthorityState({
    expertCreateMode,
    projectId,
    projectRouteRequested,
    sessionId,
  });

  const {
    activeOutput,
    activeOutputPreviewUrl,
    markReferenceGridReady,
    referenceGridReadyOutputIds: visibleReferenceGridReadyOutputIds,
  } = useAiStudioReferenceGridPreviewState({
    activeOutputById,
    activeOutputId,
    outputs,
    archivedOutputs,
  });
  const projectWorkspaceCriticalSaveSignal = useAiStudioProjectWorkspaceCriticalSaveSignal({
    projectId,
    projectRouteRequested,
    outputs,
    curatedReferenceIds,
  });
  const singleImageContextOutput = (() => {
    if (activeOutput) return activeOutput;
    const imageOutputs = outputs.filter((output) => output.mode === "image" && output.previewUrl);
    return imageOutputs.length === 1 ? (imageOutputs[0] ?? null) : null;
  })();
  const {
    selectedTool,
    setSelectedTool,
    showCreateTools,
    setShowCreateTools,
    imageReferenceImageUrl,
    imageExtraImageUrls,
    videoReferenceImageUrl,
    videoExtraImageUrls,
    motionReferenceVideoUrl,
    motionReferenceVideoPending,
    motionReferenceVideoError,
    setMotionReferenceVideoUrl,
    stageMotionVideoSelection,
    clearMotionVideoSelection,
    useReferenceImageIndicator,
    setUseReferenceImageIndicator,
    detailSelectionTarget,
    setDetailSelectionTarget,
    detailOutputId,
    setDetailOutputId,
    referenceImageUrl,
    setReferenceImageUrl,
    setImageReferenceImageUrl,
    setVideoReferenceImageUrl,
    extraImageUrls,
    setExtraImageUrl,
    setImageExtraImageUrl,
    setVideoExtraImageUrl,
    clearReferenceImages,
    toggleReferenceIndicator,
    resolveReferenceInputsForTool,
    isModelModalOpen,
    modelModalAnchor,
    modelModalContext,
    setIsModelModalOpen,
    setModelModalAnchor,
    openModelModal,
    closeModelModal,
    setAuthorityState: setReferenceSelectionAuthorityState,
    getAuthorityState: getReferenceSelectionAuthorityState,
  } = useAiStudioReferenceSelectionState({
    activeOutputPreviewUrl,
    authorityKey: createModeRuntimeAuthorityKey,
  });

  const setReferenceSelectionStateForCreateMode = useCallback(
    (
      createMode: "standard" | "pulse",
      nextState: {
        selectedTool: ToolId | null;
        showCreateTools?: boolean;
        referenceImageUrl: string | null;
        extraImageUrls: readonly (string | null)[];
        referenceImageInternalMediaRefs?: Array<InternalMediaRef | null>;
        motionReferenceVideoUrl: string | null;
        useReferenceImageIndicator?: boolean;
        detailOutputId?: string | null;
      }
    ) => {
      setReferenceSelectionAuthorityState(
        `${baseRuntimeAuthorityKey}:create:${createMode}`,
        nextState
      );
    },
    [baseRuntimeAuthorityKey, setReferenceSelectionAuthorityState]
  );

  const getReferenceSelectionStateForCreateMode = useCallback(
    (createMode: "standard" | "pulse") =>
      getReferenceSelectionAuthorityState(`${baseRuntimeAuthorityKey}:create:${createMode}`),
    [baseRuntimeAuthorityKey, getReferenceSelectionAuthorityState]
  );

  const { detailOutput, currentModelLabel, isPrimaryEditStageGenerating } =
    useAiStudioOutputDerivations({
      outputs,
      activeOutputById,
      detailSelectionTarget,
      detailOutputId,
      model,
    });
  const { hasPendingWorkflowRestore } = useAiStudioWorkflowSettings({
    projectId,
    projectRouteRequested,
    sessionId,
    isCharacterModeEnabled,
    manualWorkflowReloadRevision,
    selectedTool,
    mode,
    model,
    aspect,
    imageResolution,
    videoReferenceMode,
    lipSyncAudio,
    lipSyncTurboMode,
    videoDurationSeconds,
    videoResolution,
    videoGenerateAudio,
    videoCameraFixed,
    videoAutoFix,
    klingNegativePrompt,
    klingCfgScale,
    klingWorkflowMode,
    seedance2InputMode,
    seedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    seedance2WebSearch,
    klingShotType,
    klingVoiceIds,
    klingMultiPrompts,
    klingElements,
    setMode,
    setModelState,
    setAspect,
    setImageResolution,
    setVideoReferenceMode,
    setLipSyncAudio,
    setLipSyncTurboMode,
    setVideoDurationSeconds,
    setVideoResolution,
    setVideoGenerateAudio,
    setVideoCameraFixed,
    setVideoAutoFix,
    setKlingNegativePrompt,
    setKlingCfgScale,
    setKlingWorkflowMode,
    setSeedance2InputMode,
    setSeedance2ReferenceImageUrls,
    setSeedance2ReferenceVideoUrls,
    setSeedance2ReferenceAudioUrls,
    setSeedance2ReturnLastFrame,
    setSeedance2WebSearch,
    setKlingShotType,
    setKlingVoiceIds,
    setKlingMultiPrompts,
    setKlingElements,
  });
  const {
    activeCreatePrompt,
    createStatePrompts,
    createStateRuntime,
    setSharedPrompt,
    setStandardCreatePrompt,
    setPulseCreatePrompt,
    setEditReferenceText,
    setMusicLyricsDraft,
    setMusicPromptDraft,
    setSoundEffectsPromptDraft,
    setVideoReferenceText,
    setVoiceDesignPromptDraft,
    setVoiceScriptDraft,
  } = useAiStudioCreateRuntimePromptState({
    activePulsePresetId,
    expertCreateMode,
    setMusicPromptDraftState,
    setMusicLyricsDraftState,
    setSoundEffectsPromptDraftState,
    setVoiceDesignPromptDraftState,
    setVoiceScriptDraftState,
    pulsePrompt,
    pulseSessionInstanceId,
    setEditReferenceTextState,
    setPulsePromptState: setPulsePrompt,
    setStandardPromptState: setStandardPrompt,
    setVideoReferenceTextState,
    standardPrompt,
  });
  const {
    restoreArchivedOutput,
    restoreAllArchivedOutputs,
    setOutputs,
    addCuratedReference,
    removeCuratedReference,
    reorderCuratedReference,
    removeReferencesForDeletedMedia,
    clearCuratedReferences,
    resetReferenceGridState,
  } = useAiStudioReferenceGridStateActions({
    outputs,
    archivedOutputs,
    outputsLength: outputs.length,
    setActiveOutputId,
    setOutputsState,
    setArchivedOutputs,
    setReferenceProjectionState,
    pendingFinalizeRemovalIdsRef,
    setUiError,
  });
  useAiStudioStateEffects({
    promptRef,
    aspect,
    setAspect,
    activeOutputPreviewUrl,
    setUseReferenceImageIndicator,
    model,
    referenceImageUrl,
    extraImageUrls,
    selectedTool,
    videoReferenceMode,
    setVideoReferenceMode,
    setModel: setModelState,
    lastVideoReferenceModeRef,
    lastNonKling3VideoModelRef,
    lastNonKeyframesVideoModelRef,
    lastNonMotionVideoModelRef,
    lastNonLipSyncVideoModelRef,
    showCreateTools,
    setShowCreateTools,
    videoDurationStorageKey: VIDEO_DURATION_STORAGE_KEY,
    videoResolutionStorageKey: VIDEO_RESOLUTION_STORAGE_KEY,
    imageResolutionStorageKey: IMAGE_RESOLUTION_STORAGE_KEY,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    hasUserVideoPrefs,
    setHasUserVideoPrefs,
    setVideoGenerateAudio,
    isCharacterModeEnabled,
    mode,
    setDetailOutputId,
    setIsModelModalOpen,
    setModelModalAnchor,
    hasPendingWorkflowRestore,
  });

  const { canonicalGeneratedHydrationSettled } = useAiStudioGeneratedOutputMaintenance({
    baseRuntimeAuthorityKey,
    hasPendingWorkflowRestore,
    outputs,
    projectId,
    projectRouteRequested,
    setOutputsState,
    workspaceRuntimeKey,
  });
  useAiStudioOutputPersistenceEffects({
    outputs,
    archivedOutputs,
    setOutputsState,
    setArchivedOutputs,
    referenceProjectionState,
    setReferenceProjectionState,
    referenceProjectionStateRef,
    activeOutputState,
    archivedOutputState,
    curatedReferenceIds,
    deferProjectionPrune: !canonicalGeneratedHydrationSettled,
    setActiveOutputState,
    setArchivedOutputState,
  });

  const {
    deleteOutput,
    ensureGenerationRecord,
    ensureOutputPersisted,
    findOutputById,
    forceDeleteOutput,
    notifyGenerationFailure,
    saveActiveOutput,
    savePromptToLibrary,
    saveReferenceToLibrary,
    updateOutputById,
    updateOutputPrompt,
  } = useAiStudioStateOutputControllers({
    activeOutputByIdRef,
    activeOutputId,
    aspect,
    model,
    pendingAutoSavesRef,
    pendingFinalizeRemovalIdsRef,
    projectId,
    createPrompt: activeCreatePrompt,
    quickSlotIds: referenceProjectionState.quickSlotIds,
    setActiveOutputId,
    setActiveOutputState,
    setOutputs,
    setReferenceProjectionState,
    setSaved,
    setUiError,
    outputs,
  });

  const setReferenceSelectionStateForActiveAuthority = useCallback(
    (nextState: ReferenceSelectionAuthorityStateSeed) => {
      setReferenceSelectionAuthorityState(createModeRuntimeAuthorityKey, nextState);
    },
    [createModeRuntimeAuthorityKey, setReferenceSelectionAuthorityState]
  );

  const { reloadWorkflowFromOutput, reloadWorkflowFromStudioOutput } =
    useAiStudioWorkflowReloadController({
      beginManualWorkflowReload,
      findOutputById,
      prepareCreateCharacterWorkflowReload,
      prepareImageStyleWorkflowReload,
      prepareStandardCreateWorkflowReload,
      setAspect,
      setEditReferenceText,
      setExpertCreateMode: setExpertCreateMode ?? (() => undefined),
      setImageResolution,
      setKlingCfgScale,
      setKlingElements,
      setKlingMultiPrompts,
      setKlingNegativePrompt,
      setKlingShotType,
      setKlingVoiceIds,
      setKlingWorkflowMode,
      setModel: setModelState,
      setMotionReferenceVideoUrl,
      setMusicComposerMode: setMusicComposerModeState,
      setMusicDurationSeconds: setMusicDurationSecondsState,
      setMusicInstrumentalEnabled: setMusicInstrumentalEnabledState,
      setMusicLyricsDraft,
      setMusicPromptDraft,
      setMusicSingerEnabled: setMusicSingerEnabledState,
      setMusicSongBatchCount: setMusicSongBatchCountState,
      setReferenceSelectionState: setReferenceSelectionStateForActiveAuthority,
      setReferenceSelectionStateForCreateMode,
      setSeedance2InputMode,
      setSeedance2ReferenceAudioUrls,
      setSeedance2ReferenceImageUrls,
      setSeedance2ReferenceVideoUrls,
      setSeedance2ReturnLastFrame,
      setSeedance2WebSearch,
      setSelectedTool,
      setShowCreateTools,
      setSoundEffectsDurationSeconds: setSoundEffectsDurationSecondsState,
      setSoundEffectsLoopEnabled: setSoundEffectsLoopEnabledState,
      setSoundEffectsPromptDraft,
      setStandardCreatePrompt,
      setUiNotice,
      setVideoAutoFix,
      setVideoCameraFixed,
      setVideoDurationSeconds,
      setVideoGenerateAudio,
      setVideoReferenceMode,
      setVideoReferenceText,
      setVideoResolution,
      setVoiceChangerSource: setVoiceChangerSource ?? (() => undefined),
      setVoiceScriptDraft,
      setVoiceSelectedVoiceId: setVoiceSelectedVoiceIdState,
    });

  const {
    buildProjectWorkspaceSnapshot,
    buildSessionSnapshot,
    generateOutput,
    handleReferenceOutputMediaLoaded,
    hydrateFromSessionSnapshot,
    insertOptimisticGenerationPlaceholder,
    regenerateOutput,
    removeOptimisticGenerationPlaceholder,
    rerollOutputFromReplay,
    retryOutputStatus,
    abandonTaskOutput,
  } = useAiStudioStateRuntimeControllers({
    activeOutputId,
    activeOutputPreviewUrl,
    archivedOutputs,
    aspect,
    createPrompts: createStatePrompts,
    createRuntime: createStateRuntime,
    curatedReferenceIds,
    editReferenceText,
    extraImageUrls,
    findOutputById,
    imageResolution,
    klingCfgScale,
    klingElements,
    klingMultiPrompts,
    klingNegativePrompt,
    klingShotType,
    klingVoiceIds,
    klingWorkflowMode,
    markReferenceGridReady,
    mode,
    model,
    motionReferenceVideoUrl,
    notifyGenerationFailure,
    outputs,
    projectId,
    workspaceRuntimeKey,
    referenceImageUrl,
    removedFromAllRefsIds,
    resolveReferenceInputsForTool,
    seedance2InputMode,
    seedance2ReferenceAudioUrls,
    seedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    seedance2ReturnLastFrame,
    seedance2WebSearch,
    selectedStyleContext,
    selectedStylePrompt,
    selectedTool,
    sessionHydrationSigningRevisionRef,
    setActivePulsePresetId: setActivePulsePresetId ?? (() => undefined),
    setArchivedOutputs,
    setAspect,
    setEditReferenceText,
    setExpertCreateMode: setExpertCreateMode ?? (() => undefined),
    setExtraImageUrl,
    setImageReferenceImageUrl,
    setImageResolution,
    setKlingCfgScale,
    setKlingElements,
    setKlingMultiPrompts,
    setKlingNegativePrompt,
    setKlingShotType,
    setKlingVoiceIds,
    setKlingWorkflowMode,
    setMode,
    setModel: setModelState,
    setMotionReferenceVideoUrl,
    setOutputCollectionsForCreateMode,
    setOutputs,
    setOutputsState,
    beginPanelGeneration,
    endPanelGeneration,
    setPulseCreatePrompt,
    setPulseSessionInstanceId: setPulseSessionInstanceId ?? (() => undefined),
    setReferenceImageUrl,
    setReferenceSelectionStateForCreateMode,
    getReferenceSelectionStateForCreateMode,
    setRuntimeUiStateForCreateMode,
    setSaved,
    setSeedance2InputMode,
    setSeedance2ReferenceAudioUrls,
    setSeedance2ReferenceImageUrls,
    setSeedance2ReferenceVideoUrls,
    setSeedance2ReturnLastFrame,
    setSeedance2WebSearch,
    setSelectedTool,
    setStandardCreatePrompt,
    setUiError,
    setUiNotice,
    setVideoAutoFix,
    setVideoCameraFixed,
    setVideoDurationSeconds,
    setVideoGenerateAudio,
    setVideoReferenceMode,
    setVideoReferenceText,
    setVideoResolution,
    updateOutputById,
    useReferenceImageIndicator,
    videoAutoFix,
    videoCameraFixed,
    videoDurationSeconds,
    videoGenerateAudio,
    videoReferenceImageUrl,
    videoReferenceMode,
    lipSyncAudio,
    setLipSyncAudio,
    lipSyncTurboMode,
    setLipSyncTurboMode,
    videoReferenceText,
    videoResolution,
    ensureGenerationRecord,
  });

  const clearGenerationOutput = useAiStudioClearGenerationOutput({
    abandonTaskOutput,
    findOutputById,
    forceDeleteOutput,
    setActiveOutputId,
    updateOutputById,
  });

  const {
    addAgentPromptReference,
    addPastedPromptReference,
    addPastedMediaReference,
    insertPastedMediaReference,
    addLibraryMediaReference,
    addLibraryMediaReferenceToQuickSlot,
    addLibraryPromptReference,
    addLibraryPromptReferenceToQuickSlot,
    ingestReferenceFiles,
    addOutputsFromFiles,
    getAgentContext,
    getOutputById,
    getOutputSnapshot,
    selectActiveOutputs,
    selectArchivedOutputs,
    selectOutputById,
    subscribeOutputs,
  } = useAiStudioStateSupportControllers({
    activeOutput: singleImageContextOutput,
    archivedOutputs,
    aspect,
    mode,
    model,
    outputs,
    projectId,
    setOutputs,
    setUiError,
  });

  return {
    isPrimaryEditStageGenerating,
    promptRef,
    mode,
    setMode: setMode,
    aspect,
    setAspect,
    model,
    setModel: setModelState,
    currentModelLabel,
    activeCreatePrompt,
    setPrompt: setSharedPrompt,
    standardPrompt,
    pulsePrompt,
    setStandardCreatePrompt,
    setPulseCreatePrompt,
    outputs,
    outputOrder: activeOutputState.order,
    outputById: activeOutputState.byId,
    setOutputs,
    resetReferenceGridState,
    curatedReferenceIds,
    removedFromAllRefsIds,
    addCuratedReference,
    removeCuratedReference,
    reorderCuratedReference,
    removeReferencesForDeletedMedia,
    clearCuratedReferences,
    archivedOutputs,
    archivedOutputOrder: archivedOutputState.order,
    archivedOutputById: archivedOutputState.byId,
    selectActiveOutputs,
    selectArchivedOutputs,
    selectOutputById,
    getOutputById,
    subscribeOutputs,
    getOutputSnapshot,
    activeOutput,
    activeOutputId,
    setActiveOutputId,
    saved,
    setSaved,
    selectedTool,
    setSelectedTool,
    showCreateTools,
    setShowCreateTools,
    imageReferenceImageUrl,
    imageExtraImageUrls,
    videoReferenceImageUrl,
    videoExtraImageUrls,
    referenceImageUrl,
    setReferenceImageUrl,
    setImageReferenceImageUrl,
    setVideoReferenceImageUrl,
    extraImageUrls,
    setExtraImageUrl,
    setImageExtraImageUrl,
    setVideoExtraImageUrl,
    videoReferenceMode,
    setVideoReferenceMode,
    lipSyncAudio,
    setLipSyncAudio,
    lipSyncTurboMode,
    setLipSyncTurboMode,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    videoGenerateAudio,
    setVideoGenerateAudio,
    videoCameraFixed,
    setVideoCameraFixed,
    videoAutoFix,
    setVideoAutoFix,
    klingNegativePrompt,
    setKlingNegativePrompt,
    klingCfgScale,
    setKlingCfgScale,
    klingWorkflowMode,
    setKlingWorkflowMode,
    seedance2InputMode,
    setSeedance2InputMode,
    seedance2ReferenceImageUrls,
    setSeedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    setSeedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    setSeedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    setSeedance2ReturnLastFrame,
    seedance2WebSearch,
    setSeedance2WebSearch,
    klingShotType,
    setKlingShotType,
    klingVoiceIds,
    setKlingVoiceIds,
    klingMultiPrompts,
    setKlingMultiPrompts,
    klingElements,
    setKlingElements,
    createIsGenerating,
    editIsGenerating,
    videoIsGenerating,
    motionReferenceVideoUrl,
    motionReferenceVideoPending,
    motionReferenceVideoError,
    setMotionReferenceVideoUrl,
    stageMotionVideoSelection,
    clearMotionVideoSelection,
    editReferenceText,
    setEditReferenceText,
    videoReferenceText,
    setVideoReferenceText,
    musicPromptDraft,
    setMusicPromptDraft,
    musicLyricsDraft,
    setMusicLyricsDraft,
    musicDurationSeconds,
    setMusicDurationSeconds: setMusicDurationSecondsState,
    musicComposerMode,
    setMusicComposerMode: setMusicComposerModeState,
    musicInstrumentalEnabled,
    setMusicInstrumentalEnabled: setMusicInstrumentalEnabledState,
    musicSingerEnabled,
    setMusicSingerEnabled: setMusicSingerEnabledState,
    musicSongBatchCount,
    setMusicSongBatchCount: setMusicSongBatchCountState,
    soundEffectsPromptDraft,
    setSoundEffectsPromptDraft,
    soundEffectsDurationSeconds,
    setSoundEffectsDurationSeconds: setSoundEffectsDurationSecondsState,
    soundEffectsLoopEnabled,
    setSoundEffectsLoopEnabled: setSoundEffectsLoopEnabledState,
    voiceDesignPromptDraft,
    setVoiceDesignPromptDraft,
    voiceScriptDraft,
    setVoiceScriptDraft,
    voiceSelectedVoiceId,
    setVoiceSelectedVoiceId: setVoiceSelectedVoiceIdState,
    expertEditSessionState,
    setExpertEditSessionState,
    publishExpertEditSessionState,
    getExpertEditSessionState,
    expertEditSessionRevision,
    setSharedPrompt,
    resolvePreviewUrlById,
    useReferenceImageIndicator,
    detailOutput,
    detailSelectionTarget,
    setDetailSelectionTarget,
    detailOutputId,
    setDetailOutputId,
    isModelModalOpen,
    modelModalAnchor,
    modelModalContext,
    generateOutput,
    regenerateOutput,
    reloadWorkflowFromOutput,
    reloadWorkflowFromStudioOutput,
    rerollOutputFromReplay,
    insertOptimisticGenerationPlaceholder,
    removeOptimisticGenerationPlaceholder,
    updateOutputById,
    notifyGenerationFailure,
    saveActiveOutput,
    ensureOutputPersisted,
    saveReferenceToLibrary,
    savePromptToLibrary,
    addAgentPromptReference,
    addPastedPromptReference,
    addPastedMediaReference,
    insertPastedMediaReference,
    addLibraryMediaReference,
    addLibraryMediaReferenceToQuickSlot,
    addLibraryPromptReference,
    addLibraryPromptReferenceToQuickSlot,
    ingestReferenceFiles,
    addOutputsFromFiles,
    buildProjectWorkspaceSnapshot,
    buildSessionSnapshot,
    projectWorkspaceCriticalSaveSignal,
    hydrateFromSessionSnapshot,
    toggleReferenceIndicator,
    clearReferenceImages,
    openModelModal,
    closeModelModal,
    updateOutputPrompt,
    deleteOutput,
    clearGenerationOutput,
    restoreArchivedOutput,
    restoreAllArchivedOutputs,
    uiError,
    setUiError,
    uiNotice,
    setUiNotice,
    getDefaultDurationSeconds: getDefaultDurationSecondsForModel,
    getAgentContext,
    onReferenceOutputMediaLoaded: handleReferenceOutputMediaLoaded,
    referenceGridReadyOutputIds: visibleReferenceGridReadyOutputIds,
    retryOutputStatus,
  };
};
