/**
 * Shared state + actions for AI Studio.
 * Encapsulates creation/regeneration flows, output book-keeping, and modal state so the page can stay declarative.
 */
import { useCallback, useRef, useState } from "react";
import { StudioOutput } from "../types";
import { resolvePreviewUrlById } from "../logic/stateParsers";
import { useAiStudioCreationState } from "./useAiStudioCreationState";
import { useAiStudioPersistenceActions } from "./useAiStudioPersistenceActions";
import { useAiStudioOutputLifecycle } from "./useAiStudioOutputLifecycle";
import { useAiStudioGenerationPromptComposer } from "./useAiStudioGenerationPromptComposer";
import { useAiStudioOutputDerivations } from "./useAiStudioOutputDerivations";
import { useAiStudioReferenceIngestionActions } from "./useAiStudioReferenceIngestionActions";
import { useAiStudioReferenceGridStateActions } from "./useAiStudioReferenceGridStateActions";
import { useAiStudioReferenceSelectionState } from "./useAiStudioReferenceSelectionState";
import { useAiStudioTaskOrchestration } from "./useAiStudioTaskOrchestration";
import { useAiStudioWorkflowSettings } from "./useAiStudioWorkflowSettings";
import { useAiStudioStateEffects } from "./useAiStudioStateEffects";
import { useAiStudioOutputCollectionState } from "./useAiStudioOutputCollectionState";
import { useAiStudioOptimisticPlaceholderActions } from "./useAiStudioOptimisticPlaceholderActions";
import { useAiStudioOutputStoreSelectors } from "./useAiStudioOutputStoreSelectors";
import { useAiStudioOutputPersistenceEffects } from "./useAiStudioOutputPersistenceEffects";
import { useAiStudioReferenceGridPreviewState } from "./useAiStudioReferenceGridPreviewState";
import {
  DEFAULT_REFERENCE_GRID_ACTIVE_LIMIT,
  getDefaultDurationSecondsForModel,
  IMAGE_RESOLUTION_STORAGE_KEY,
  REFERENCE_GRID_ACTIVE_LIMIT,
  REFERENCE_GRID_ARCHIVE_PREVIEW_KEEP_COUNT,
  REFERENCE_GRID_FLAG_SOFT_ARCHIVE,
  VIDEO_DURATION_STORAGE_KEY,
  VIDEO_RESOLUTION_STORAGE_KEY,
} from "./aiStudioStateConfig";
import { useAiStudioDeleteOutputController } from "./useAiStudioDeleteOutputController";
import { useAiStudioFastOutputAccess } from "./useAiStudioFastOutputAccess";
import { useAiStudioRerollController } from "./useAiStudioRerollController";
import { useAiStudioSessionSnapshotController } from "./useAiStudioSessionSnapshotController";
import { useAiStudioStableTextSetters } from "./useAiStudioStableTextSetters";
import { useAiStudioSubmissionReferenceResolver } from "./useAiStudioSubmissionReferenceResolver";
import {
  createEmptyReferenceProjectionState,
  type ReferenceProjectionState,
} from "../reference-projections";
/**
 * Provides AI Studio state and handlers for create/regenerate flows.
 */
export const useAiStudioState = ({
  sessionId = null,
  isCharacterModeEnabled = false,
  selectedStylePrompt = null,
  selectedStyleContext = null,
}: {
  sessionId?: string | null;
  isCharacterModeEnabled?: boolean;
  selectedStylePrompt?: string | null;
  selectedStyleContext?: StudioOutput["styleContext"] | null;
} = {}) => {
  const {
    promptRef,
    mode,
    setMode,
    aspect,
    setAspect,
    model,
    setModelState,
    prompt,
    setPrompt,
    editReferenceText,
    setEditReferenceTextState,
    videoReferenceText,
    setVideoReferenceTextState,
    expertEditSessionState,
    setExpertEditSessionState,
    videoReferenceMode,
    setVideoReferenceMode,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    hasUserVideoPrefs,
    setHasUserVideoPrefs,
    videoGenerateAudio,
    setVideoGenerateAudio,
    videoCameraFixed,
    setVideoCameraFixed,
    videoAutoFix,
    setVideoAutoFix,
    klingNegativePrompt,
    setKlingNegativePrompt,
    klingCfgScale,
    setKlingCfgScale,
    klingWorkflowMode,
    setKlingWorkflowMode,
    seedance2InputMode,
    setSeedance2InputMode,
    seedance2ReferenceImageUrls,
    setSeedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    setSeedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    setSeedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    setSeedance2ReturnLastFrame,
    seedance2WebSearch,
    setSeedance2WebSearch,
    klingShotType,
    setKlingShotType,
    klingVoiceIds,
    setKlingVoiceIds,
    klingMultiPrompts,
    setKlingMultiPrompts,
    klingElements,
    setKlingElements,
    createIsGenerating,
    editIsGenerating,
    videoIsGenerating,
    setPanelGenerating,
    uiError,
    setUiError,
    uiNotice,
    setUiNotice,
    lastVideoReferenceModeRef,
    lastNonKling3VideoModelRef,
    lastNonKeyframesVideoModelRef,
    lastNonMotionVideoModelRef,
  } = useAiStudioCreationState();

  const {
    activeOutputState,
    setActiveOutputState,
    archivedOutputState,
    setArchivedOutputState,
    activeOutputByIdRef,
    outputs,
    archivedOutputs,
    activeOutputById,
    setOutputsState,
    setArchivedOutputs,
  } = useAiStudioOutputCollectionState();
  const [activeOutputId, setActiveOutputId] = useState<string | null>(null);
  const [referenceProjectionState, setReferenceProjectionState] =
    useState<ReferenceProjectionState>(createEmptyReferenceProjectionState);
  const referenceProjectionStateRef = useRef<ReferenceProjectionState>(referenceProjectionState);
  const curatedReferenceIds = referenceProjectionState.quickSlotIds;
  const removedFromAllRefsIds = referenceProjectionState.removedFromAllRefsIds;
  const [saved, setSaved] = useState(false);
  const pendingAutoSavesRef = useRef<Record<string, unknown>>({});
  const pendingFinalizeRemovalIdsRef = useRef<Set<string>>(new Set());
  const sessionHydrationSigningRevisionRef = useRef(0);
  const {
    activeOutput,
    activeOutputPreviewUrl,
    markReferenceGridReady,
    referenceGridReadyOutputIds: visibleReferenceGridReadyOutputIds,
  } = useAiStudioReferenceGridPreviewState({
    activeOutputById,
    activeOutputId,
    outputs,
    archivedOutputs,
  });
  const {
    selectedTool,
    setSelectedTool,
    showCreateTools,
    setShowCreateTools,
    imageReferenceImageUrl,
    imageExtraImageUrls,
    videoReferenceImageUrl,
    videoExtraImageUrls,
    motionReferenceVideoUrl,
    setMotionReferenceVideoUrl,
    useReferenceImageIndicator,
    setUseReferenceImageIndicator,
    detailOutputId,
    setDetailOutputId,
    referenceImageUrl,
    setReferenceImageUrl,
    setImageReferenceImageUrl,
    setVideoReferenceImageUrl,
    extraImageUrls,
    setExtraImageUrl,
    setImageExtraImageUrl,
    setVideoExtraImageUrl,
    clearReferenceImages,
    toggleReferenceIndicator,
    resolveReferenceInputsForTool,
    isModelModalOpen,
    modelModalAnchor,
    modelModalContext,
    setIsModelModalOpen,
    setModelModalAnchor,
    openModelModal,
    closeModelModal,
  } = useAiStudioReferenceSelectionState({
    activeOutputPreviewUrl,
  });

  const { detailOutput, currentModelLabel, isPrimaryEditStageGenerating } =
    useAiStudioOutputDerivations({ outputs, activeOutputById, detailOutputId, model });
  const { hasPendingWorkflowRestore } = useAiStudioWorkflowSettings({
    sessionId,
    selectedTool,
    mode,
    model,
    aspect,
    imageResolution,
    videoReferenceMode,
    videoDurationSeconds,
    videoResolution,
    videoGenerateAudio,
    videoCameraFixed,
    videoAutoFix,
    klingNegativePrompt,
    klingCfgScale,
    klingWorkflowMode,
    seedance2InputMode,
    seedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    seedance2WebSearch,
    klingShotType,
    klingVoiceIds,
    klingMultiPrompts,
    klingElements,
    setMode,
    setModelState,
    setAspect,
    setImageResolution,
    setVideoReferenceMode,
    setVideoDurationSeconds,
    setVideoResolution,
    setVideoGenerateAudio,
    setVideoCameraFixed,
    setVideoAutoFix,
    setKlingNegativePrompt,
    setKlingCfgScale,
    setKlingWorkflowMode,
    setSeedance2InputMode,
    setSeedance2ReferenceImageUrls,
    setSeedance2ReferenceVideoUrls,
    setSeedance2ReferenceAudioUrls,
    setSeedance2ReturnLastFrame,
    setSeedance2WebSearch,
    setKlingShotType,
    setKlingVoiceIds,
    setKlingMultiPrompts,
    setKlingElements,
  });
  const { setSharedPrompt, setEditReferenceText, setVideoReferenceText } =
    useAiStudioStableTextSetters({
      setPrompt,
      setEditReferenceTextState,
      setVideoReferenceTextState,
    });
  const {
    archiveOlderOutputs,
    restoreArchivedOutput,
    restoreAllArchivedOutputs,
    setOutputs,
    addCuratedReference,
    removeCuratedReference,
    reorderCuratedReference,
    clearCuratedReferences,
    resetReferenceGridState,
  } = useAiStudioReferenceGridStateActions({
    activeOutputId,
    outputsLength: outputs.length,
    setActiveOutputId,
    setOutputsState,
    setArchivedOutputs,
    setReferenceProjectionState,
    pendingFinalizeRemovalIdsRef,
    config: {
      softArchiveEnabled: REFERENCE_GRID_FLAG_SOFT_ARCHIVE,
      activeLimit: REFERENCE_GRID_ACTIVE_LIMIT,
      archivePreviewKeepCount: REFERENCE_GRID_ARCHIVE_PREVIEW_KEEP_COUNT,
      defaultActiveLimit: DEFAULT_REFERENCE_GRID_ACTIVE_LIMIT,
    },
  });
  const { findActiveOutputById, updateActiveOutputById } = useAiStudioFastOutputAccess({
    activeOutputByIdRef,
    setActiveOutputState,
  });

  useAiStudioStateEffects({
    promptRef,
    aspect,
    setAspect,
    activeOutputPreviewUrl,
    setUseReferenceImageIndicator,
    model,
    referenceImageUrl,
    extraImageUrls,
    selectedTool,
    videoReferenceMode,
    setVideoReferenceMode,
    setModel: setModelState,
    lastVideoReferenceModeRef,
    lastNonKling3VideoModelRef,
    lastNonKeyframesVideoModelRef,
    lastNonMotionVideoModelRef,
    showCreateTools,
    setShowCreateTools,
    videoDurationStorageKey: VIDEO_DURATION_STORAGE_KEY,
    videoResolutionStorageKey: VIDEO_RESOLUTION_STORAGE_KEY,
    imageResolutionStorageKey: IMAGE_RESOLUTION_STORAGE_KEY,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    hasUserVideoPrefs,
    setHasUserVideoPrefs,
    setVideoGenerateAudio,
    isCharacterModeEnabled,
    mode,
    setDetailOutputId,
    setIsModelModalOpen,
    setModelModalAnchor,
    hasPendingWorkflowRestore,
  });

  useAiStudioOutputPersistenceEffects({
    outputs,
    archivedOutputs,
    setOutputsState,
    setArchivedOutputs,
    referenceProjectionState,
    setReferenceProjectionState,
    referenceProjectionStateRef,
    activeOutputOrder: activeOutputState.order,
    archivedOutputOrder: archivedOutputState.order,
    curatedReferenceIds,
    setActiveOutputState,
    setArchivedOutputState,
    setOutputs,
  });

  const {
    updateOutputById,
    findOutputById,
    deleteOutput: deleteOutputFromLifecycle,
    notifyGenerationFailure,
    updateOutputPrompt,
  } = useAiStudioOutputLifecycle({
    outputs,
    setOutputs,
    updateOutputByIdFast: updateActiveOutputById,
    findOutputByIdFast: findActiveOutputById,
    activeOutputId,
    setActiveOutputId,
    pendingAutoSavesRef,
  });
  const { deleteOutput } = useAiStudioDeleteOutputController({
    quickSlotIds: referenceProjectionState.quickSlotIds,
    setReferenceProjectionState,
    setActiveOutputId,
    deleteOutputFromLifecycle,
    pendingFinalizeRemovalIdsRef,
  });

  const {
    ensureGenerationRecord,
    ensureOutputPersisted,
    saveActiveOutput,
    saveReferenceToLibrary,
    savePromptReference,
    savePromptToLibrary,
  } = useAiStudioPersistenceActions({
    findOutputById,
    updateOutputById,
    setUiError,
    setOutputs,
    setSaved,
    activeOutputId,
    model,
    aspect,
    prompt,
  });

  const { submitTask, onReferenceOutputMediaLoaded, retryOutputStatus } =
    useAiStudioTaskOrchestration({
      taskSubmissionConfig: {
        aspect,
        mode,
        model,
        prompt,
        selectedTool,
        imageResolution,
        videoDurationSeconds,
        videoResolution,
        videoGenerateAudio,
        videoReferenceMode,
        videoReferenceImageUrl,
        motionReferenceVideoUrl,
        videoCameraFixed,
        videoAutoFix,
        seedance2InputMode,
        seedance2ReferenceImageUrls,
        seedance2ReferenceVideoUrls,
        seedance2ReferenceAudioUrls,
        seedance2ReturnLastFrame,
        seedance2WebSearch,
        klingNegativePrompt,
        klingCfgScale,
        klingWorkflowMode,
        klingShotType,
        klingVoiceIds,
        klingMultiPrompts,
        klingElements,
        setPanelGenerating,
        setUiError,
        setUiNotice,
        setOutputs,
        setSaved,
        getDefaultDurationSeconds: getDefaultDurationSecondsForModel,
        notifyGenerationFailure,
        updateOutputById,
        ensureGenerationRecord,
      },
      outputs,
      findOutputById,
      setPrimaryEditReferenceImageUrl: setImageReferenceImageUrl,
    });

  const handleReferenceOutputMediaLoaded = useCallback(
    (outputId: string) => {
      onReferenceOutputMediaLoaded(outputId);
      markReferenceGridReady(outputId);
    },
    [markReferenceGridReady, onReferenceOutputMediaLoaded]
  );
  const { resolveSubmissionReferenceInputsForTool } = useAiStudioSubmissionReferenceResolver({
    resolveReferenceInputsForTool,
  });
  const { generateOutput, regenerateOutput } = useAiStudioGenerationPromptComposer({
    model,
    prompt,
    editReferenceText,
    videoReferenceText,
    selectedStylePrompt,
    selectedStyleContext,
    selectedTool,
    videoReferenceMode,
    useReferenceImageIndicator,
    activeOutputPreviewUrl,
    resolveReferenceInputsForTool: resolveSubmissionReferenceInputsForTool,
    submitTask,
  });
  const { rerollOutputFromReplay } = useAiStudioRerollController({
    findOutputById,
    setUiNotice,
    submitTask,
  });
  const { insertOptimisticGenerationPlaceholder, removeOptimisticGenerationPlaceholder } =
    useAiStudioOptimisticPlaceholderActions({
      mode,
      selectedTool,
      aspect,
      model,
      setOutputs,
      setSaved,
    });

  const { hydrateFromSessionSnapshot, buildSessionSnapshot } = useAiStudioSessionSnapshotController(
    {
      mode,
      selectedTool,
      prompt,
      model,
      aspect,
      referenceImageUrl,
      extraImageUrls,
      editReferenceText,
      videoReferenceText,
      videoReferenceMode,
      videoDurationSeconds,
      videoResolution,
      imageResolution,
      videoGenerateAudio,
      videoCameraFixed,
      videoAutoFix,
      klingNegativePrompt,
      klingCfgScale,
      klingWorkflowMode,
      seedance2InputMode,
      seedance2ReferenceImageUrls,
      seedance2ReferenceVideoUrls,
      seedance2ReferenceAudioUrls,
      seedance2ReturnLastFrame,
      seedance2WebSearch,
      klingShotType,
      klingVoiceIds,
      klingMultiPrompts,
      klingElements,
      motionReferenceVideoUrl,
      outputs,
      archivedOutputs,
      activeOutputId,
      curatedReferenceIds,
      removedFromAllRefsIds,
      sessionHydrationSigningRevisionRef,
      setMode,
      setSelectedTool,
      setSharedPrompt,
      setModel: setModelState,
      setAspect,
      setReferenceImageUrl,
      setExtraImageUrl,
      setEditReferenceText,
      setVideoReferenceText,
      setVideoReferenceMode,
      setVideoDurationSeconds,
      setVideoResolution,
      setImageResolution,
      setVideoGenerateAudio,
      setVideoCameraFixed,
      setVideoAutoFix,
      setKlingNegativePrompt,
      setKlingCfgScale,
      setKlingWorkflowMode,
      setSeedance2InputMode,
      setSeedance2ReferenceImageUrls,
      setSeedance2ReferenceVideoUrls,
      setSeedance2ReferenceAudioUrls,
      setSeedance2ReturnLastFrame,
      setSeedance2WebSearch,
      setKlingShotType,
      setKlingVoiceIds,
      setKlingMultiPrompts,
      setKlingElements,
      setMotionReferenceVideoUrl,
      setOutputsState,
      setArchivedOutputs,
      setReferenceProjectionState,
      setActiveOutputId,
      setSaved,
    }
  );

  const {
    addAgentPromptReference,
    addPastedPromptReference,
    addPastedMediaReference,
    addLibraryMediaReference,
    addLibraryMediaReferenceToQuickSlot,
    addLibraryPromptReference,
    addLibraryPromptReferenceToQuickSlot,
    addOutputsFromFiles,
    getAgentContext,
  } = useAiStudioReferenceIngestionActions({
    mode,
    aspect,
    model,
    setOutputs,
    updateOutputById,
    setSharedPrompt,
    setUiError,
  });

  const {
    selectActiveOutputs,
    selectArchivedOutputs,
    getOutputById,
    subscribeOutputs,
    getOutputSnapshot,
    selectOutputById,
  } = useAiStudioOutputStoreSelectors({
    outputs,
    archivedOutputs,
  });

  return {
    isPrimaryEditStageGenerating,
    promptRef,
    mode,
    setMode: setMode,
    aspect,
    setAspect,
    model,
    setModel: setModelState,
    currentModelLabel,
    prompt,
    setPrompt,
    outputs,
    outputOrder: activeOutputState.order,
    outputById: activeOutputState.byId,
    setOutputs,
    resetReferenceGridState,
    curatedReferenceIds,
    removedFromAllRefsIds,
    addCuratedReference,
    removeCuratedReference,
    reorderCuratedReference,
    clearCuratedReferences,
    archivedOutputs,
    archivedOutputOrder: archivedOutputState.order,
    archivedOutputById: archivedOutputState.byId,
    selectActiveOutputs,
    selectArchivedOutputs,
    selectOutputById,
    getOutputById,
    subscribeOutputs,
    getOutputSnapshot,
    activeOutput,
    activeOutputId,
    setActiveOutputId,
    saved,
    setSaved,
    selectedTool,
    setSelectedTool,
    showCreateTools,
    setShowCreateTools,
    imageReferenceImageUrl,
    imageExtraImageUrls,
    videoReferenceImageUrl,
    videoExtraImageUrls,
    referenceImageUrl,
    setReferenceImageUrl,
    setImageReferenceImageUrl,
    setVideoReferenceImageUrl,
    extraImageUrls,
    setExtraImageUrl,
    setImageExtraImageUrl,
    setVideoExtraImageUrl,
    videoReferenceMode,
    setVideoReferenceMode,
    videoDurationSeconds,
    setVideoDurationSeconds,
    videoResolution,
    setVideoResolution,
    imageResolution,
    setImageResolution,
    videoGenerateAudio,
    setVideoGenerateAudio,
    videoCameraFixed,
    setVideoCameraFixed,
    videoAutoFix,
    setVideoAutoFix,
    klingNegativePrompt,
    setKlingNegativePrompt,
    klingCfgScale,
    setKlingCfgScale,
    klingWorkflowMode,
    setKlingWorkflowMode,
    seedance2InputMode,
    setSeedance2InputMode,
    seedance2ReferenceImageUrls,
    setSeedance2ReferenceImageUrls,
    seedance2ReferenceVideoUrls,
    setSeedance2ReferenceVideoUrls,
    seedance2ReferenceAudioUrls,
    setSeedance2ReferenceAudioUrls,
    seedance2ReturnLastFrame,
    setSeedance2ReturnLastFrame,
    seedance2WebSearch,
    setSeedance2WebSearch,
    klingShotType,
    setKlingShotType,
    klingVoiceIds,
    setKlingVoiceIds,
    klingMultiPrompts,
    setKlingMultiPrompts,
    klingElements,
    setKlingElements,
    createIsGenerating,
    editIsGenerating,
    videoIsGenerating,
    motionReferenceVideoUrl,
    setMotionReferenceVideoUrl,
    editReferenceText,
    setEditReferenceText,
    videoReferenceText,
    setVideoReferenceText,
    expertEditSessionState,
    setExpertEditSessionState,
    setSharedPrompt,
    resolvePreviewUrlById,
    useReferenceImageIndicator,
    detailOutput,
    detailOutputId,
    setDetailOutputId,
    isModelModalOpen,
    modelModalAnchor,
    modelModalContext,
    generateOutput,
    regenerateOutput,
    rerollOutputFromReplay,
    insertOptimisticGenerationPlaceholder,
    removeOptimisticGenerationPlaceholder,
    saveActiveOutput,
    ensureOutputPersisted,
    saveReferenceToLibrary,
    savePromptReference,
    savePromptToLibrary,
    addAgentPromptReference,
    addPastedPromptReference,
    addPastedMediaReference,
    addLibraryMediaReference,
    addLibraryMediaReferenceToQuickSlot,
    addLibraryPromptReference,
    addLibraryPromptReferenceToQuickSlot,
    addOutputsFromFiles,
    buildSessionSnapshot,
    hydrateFromSessionSnapshot,
    toggleReferenceIndicator,
    clearReferenceImages,
    openModelModal,
    closeModelModal,
    updateOutputPrompt,
    deleteOutput,
    restoreArchivedOutput,
    restoreAllArchivedOutputs,
    archiveOlderOutputs,
    uiError,
    setUiError,
    uiNotice,
    setUiNotice,
    getDefaultDurationSeconds: getDefaultDurationSecondsForModel,
    getAgentContext,
    onReferenceOutputMediaLoaded: handleReferenceOutputMediaLoaded,
    referenceGridReadyOutputIds: visibleReferenceGridReadyOutputIds,
    retryOutputStatus,
  };
};
