const FAL_ROUTE_INVENTORY = [
  {
    fileBase: "bria-background-remove",
    modelId: "fal-ai/bria/background/remove",
    provider: "fal",
    routeLabel: "Fal Bria background remove",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "flux2klein",
    modelId: "fal-ai/flux-2/klein/9b",
    provider: "fal",
    routeLabel: "Fal FLUX 2 Klein",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "kie-kling",
    modelId: "kie-ai/kling-3.0",
    provider: "kie",
    routeLabel: "Kie Kling 3.0",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "kie-gpt-image-2",
    modelId: "kie-ai/gpt-image-2-text-to-image",
    provider: "kie",
    routeLabel: "Kie GPT Image 2 Text to Image",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "kie-gpt-image-2-edit",
    modelId: "kie-ai/gpt-image-2-image-to-image",
    provider: "kie",
    routeLabel: "Kie GPT Image 2 Image to Image",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "kie-seedance-2",
    modelId: "kie-ai/seedance-2",
    provider: "kie",
    routeLabel: "Kie Seedance 2.0",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "kie-seedance-2-fast",
    modelId: "kie-ai/seedance-2-fast",
    provider: "kie",
    routeLabel: "Kie Seedance 2.0 Fast",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "kie-veo",
    modelId: "kie-ai/veo-3.1-fast-i2v",
    provider: "kie",
    routeLabel: "Kie Veo 3.1 Fast I2V",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "nano-banana-2",
    modelId: "fal-ai/nano-banana-2",
    provider: "fal",
    routeLabel: "Fal Nano Banana 2",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "nano-banana-2-edit",
    modelId: "fal-ai/nano-banana-2/edit",
    provider: "fal",
    routeLabel: "Fal Nano Banana 2 Edit",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "nano-banana-pro",
    modelId: "fal-ai/nano-banana-pro",
    provider: "fal",
    routeLabel: "Fal Nano Banana Pro",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "nano-banana-pro-edit",
    modelId: "fal-ai/nano-banana-pro/edit",
    provider: "fal",
    routeLabel: "Fal Nano Banana Pro edit",
    statusRouteLabel: "Fal Nano Banana Pro Edit",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "omnihuman-v15",
    modelId: "fal-ai/bytedance/omnihuman/v1.5",
    provider: "fal",
    routeLabel: "Fal OmniHuman v1.5",
    submitTimeoutMs: 20000,
    statusTimeoutMs: 60000,
    validator: "generic",
  },
  {
    fileBase: "seedream",
    modelId: "fal-ai/bytedance/seedream/v4.5/text-to-image",
    provider: "fal",
    routeLabel: "Fal Seedream",
    submitTimeoutMs: 60000,
    statusTimeoutMs: 60000,
    validator: "seedream-image",
  },
  {
    fileBase: "seedream-edit",
    modelId: "fal-ai/bytedance/seedream/v4.5/edit",
    provider: "fal",
    routeLabel: "Fal Seedream edit",
    submitTimeoutMs: 60000,
    statusTimeoutMs: 60000,
    validator: "seedream-edit",
    reExportValidator: true,
  },
  {
    fileBase: "seedream-v5-lite",
    modelId: "fal-ai/bytedance/seedream/v5/lite/text-to-image",
    provider: "fal",
    routeLabel: "Fal Seedream 5 Lite",
    submitTimeoutMs: 60000,
    statusTimeoutMs: 60000,
    validator: "seedream-image",
  },
  {
    fileBase: "seedream-v5-lite-edit",
    modelId: "fal-ai/bytedance/seedream/v5/lite/edit",
    provider: "fal",
    routeLabel: "Fal Seedream 5 Lite edit",
    submitTimeoutMs: 60000,
    statusTimeoutMs: 60000,
    validator: "seedream-edit",
  },
];

const listExpectedFalRouteFiles = () =>
  [
    ...FAL_ROUTE_INVENTORY.flatMap((entry) => [
      `${entry.fileBase}-submit.ts`,
      `${entry.fileBase}-status.ts`,
    ]),
    "upload-url.ts",
    "webhook.ts",
  ].sort((a, b) => a.localeCompare(b));

module.exports = {
  FAL_ROUTE_INVENTORY,
  listExpectedFalRouteFiles,
};
